//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huaanClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("huaanClient.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 旷工 的本地化字符串。
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的磁盘，无法保存数据 的本地化字符串。
        /// </summary>
        internal static string AllDriveIsNotAvailable {
            get {
                return ResourceManager.GetString("AllDriveIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度考勤报表 的本地化字符串。
        /// </summary>
        internal static string AttendanceDataMonthlyExportFileName {
            get {
                return ResourceManager.GetString("AttendanceDataMonthlyExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name,personId,department,Employee_code,nowdate,Attendance,latedata,Leaveearlydata,AbsenteeismCount,LeaveCount 的本地化字符串。
        /// </summary>
        internal static string AttendanceDataMonthlyKeys {
            get {
                return ResourceManager.GetString("AttendanceDataMonthlyKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名,用户编码,部门,员工编号,考勤日期,出勤(天),迟到次数/总时长(分钟),早退次数/总时长(分钟),旷工天数,请假天数 的本地化字符串。
        /// </summary>
        internal static string AttendanceDataMonthlyNames {
            get {
                return ResourceManager.GetString("AttendanceDataMonthlyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name,department,Employee_code,Date,Punchinformation,Punchinformation1,Punchinformation2,Punchinformation22,Shiftinformation,Duration,late,Leaveearly,workOvertime,isAbsenteeism,temperature 的本地化字符串。
        /// </summary>
        internal static string AttendanceKeys {
            get {
                return ResourceManager.GetString("AttendanceKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名,部门,员工编号,考勤日期,上班打卡,下班打卡,上班打卡2,下班打卡2,班次信息,应出勤时间(小时),迟到(分钟),早退(分钟),加班(分钟),是否旷工,体温 的本地化字符串。
        /// </summary>
        internal static string AttendanceNames {
            get {
                return ResourceManager.GetString("AttendanceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入模板 的本地化字符串。
        /// </summary>
        internal static string BatchImportModel {
            get {
                return ResourceManager.GetString("BatchImportModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入结果 的本地化字符串。
        /// </summary>
        internal static string BatchImportResult {
            get {
                return ResourceManager.GetString("BatchImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓拍记录 的本地化字符串。
        /// </summary>
        internal static string CaptureDataExportDefaultFileName {
            get {
                return ResourceManager.GetString("CaptureDataExportDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 person_name,person_id,addr_name,time,match_status,wg_card_id,match_failed_reson,exist_mask,body_temp,device_sn,idcard_number,idcard_name,QRcodestatus,trip_infor,closeup 的本地化字符串。
        /// </summary>
        internal static string CaptureRecordColumnKeys {
            get {
                return ResourceManager.GetString("CaptureRecordColumnKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名,ID,设备名称,刷卡时间,对比分数,门禁卡号,比对失败原因,是否佩戴口罩,体温,设备序列号,证件编号,证件姓名,健康码状态,行程信息,抓拍图片路径 的本地化字符串。
        /// </summary>
        internal static string CaptureRecordColumnNames {
            get {
                return ResourceManager.GetString("CaptureRecordColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认新密码 的本地化字符串。
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入的新密码不同 的本地化字符串。
        /// </summary>
        internal static string ConfirmNewPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据库失败: {0} 的本地化字符串。
        /// </summary>
        internal static string ConnectDbFailed {
            get {
                return ResourceManager.GetString("ConnectDbFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要导出的数据超过10000条 的本地化字符串。
        /// </summary>
        internal static string DatasetIsTooBig {
            get {
                return ResourceManager.GetString("DatasetIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假 的本地化字符串。
        /// </summary>
        internal static string DailyAttendanceSheetName {
            get {
                return ResourceManager.GetString("DailyAttendanceSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请假.
        /// </summary>
        internal static string DayOff {
            get {
                return ResourceManager.GetString("DayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string DefaultCompanyName {
            get {
                return ResourceManager.GetString("DefaultCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义内容 的本地化字符串。
        /// </summary>
        internal static string DefaultCustomerText {
            get {
                return ResourceManager.GetString("DefaultCustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下属部门 的本地化字符串。
        /// </summary>
        internal static string DefaultDepartmentName {
            get {
                return ResourceManager.GetString("DefaultDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        internal static string DefaultEmployeeType {
            get {
                return ResourceManager.GetString("DefaultEmployeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认考勤组 的本地化字符串。
        /// </summary>
        internal static string DefaultShiftGroupName {
            get {
                return ResourceManager.GetString("DefaultShiftGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班次 的本地化字符串。
        /// </summary>
        internal static string DefaultShiftName {
            get {
                return ResourceManager.GetString("DefaultShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备离线 的本地化字符串。
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开文件，请确保文件没有被其他程序打开 的本地化字符串。
        /// </summary>
        internal static string ExcelCantBeAccessed {
            get {
                return ResourceManager.GetString("ExcelCantBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel文件 (*.xlsx)|*.xlsx 的本地化字符串。
        /// </summary>
        internal static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入结果 的本地化字符串。
        /// </summary>
        internal static string ExcelImportLogFileName {
            get {
                return ResourceManager.GetString("ExcelImportLogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件为空 的本地化字符串。
        /// </summary>
        internal static string ExcelIsEmpty {
            get {
                return ResourceManager.GetString("ExcelIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误：{0} 的本地化字符串。
        /// </summary>
        internal static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件失败：{0} 的本地化字符串。
        /// </summary>
        internal static string ExportFileFailedWithError {
            get {
                return ResourceManager.GetString("ExportFileFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件成功 的本地化字符串。
        /// </summary>
        internal static string ExportFileSucceed {
            get {
                return ResourceManager.GetString("ExportFileSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿码 的本地化字符串。
        /// </summary>
        internal static string GreenCode {
            get {
                return ResourceManager.GetString("GreenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片缺失 的本地化字符串。
        /// </summary>
        internal static string ImageMissing {
            get {
                return ResourceManager.GetString("ImageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化数据库错误 的本地化字符串。
        /// </summary>
        internal static string InitializeDbFailed {
            get {
                return ResourceManager.GetString("InitializeDbFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化数据库 的本地化字符串。
        /// </summary>
        internal static string InitializingDb {
            get {
                return ResourceManager.GetString("InitializingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP已存在 的本地化字符串。
        /// </summary>
        internal static string IPAlreadyExists {
            get {
                return ResourceManager.GetString("IPAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登录... 的本地化字符串。
        /// </summary>
        internal static string LoginInProgress {
            get {
                return ResourceManager.GetString("LoginInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功 的本地化字符串。
        /// </summary>
        internal static string LoginSucceed {
            get {
                return ResourceManager.GetString("LoginSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string MenuItemCopyImage {
            get {
                return ResourceManager.GetString("MenuItemCopyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功:{0},失败:{1}，是否保存导入结果？ 的本地化字符串。
        /// </summary>
        internal static string MessageSaveImportLog {
            get {
                return ResourceManager.GetString("MessageSaveImportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能和旧密码相同 的本地化字符串。
        /// </summary>
        internal static string NewPasswordCanotBeSameAsOld {
            get {
                return ResourceManager.GetString("NewPasswordCanotBeSameAsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要导出的数据为空 的本地化字符串。
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片不合法，图片必须满足正面且只有唯一人脸 的本地化字符串。
        /// </summary>
        internal static string PhotoTakenNotQualified {
            get {
                return ResourceManager.GetString("PhotoTakenNotQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在切换... 的本地化字符串。
        /// </summary>
        internal static string PromptSwitchingCamera {
            get {
                return ResourceManager.GetString("PromptSwitchingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红码 的本地化字符串。
        /// </summary>
        internal static string RedCode {
            get {
                return ResourceManager.GetString("RedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示在资源管理器中 的本地化字符串。
        /// </summary>
        internal static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateZn.xlsx 的本地化字符串。
        /// </summary>
        internal static string SrcStaffTemplateFileName {
            get {
                return ResourceManager.GetString("SrcStaffTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工编号已经存在 的本地化字符串。
        /// </summary>
        internal static string StaffCodeExists {
            get {
                return ResourceManager.GetString("StaffCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工编号不能为空 的本地化字符串。
        /// </summary>
        internal static string StaffCodeIsEmpty {
            get {
                return ResourceManager.GetString("StaffCodeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员信息 的本地化字符串。
        /// </summary>
        internal static string StaffExportExcelName {
            get {
                return ResourceManager.GetString("StaffExportExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片不合符要求 的本地化字符串。
        /// </summary>
        internal static string StaffImageInValid {
            get {
                return ResourceManager.GetString("StaffImageInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name,Email,phone,Employee_code,picture,publish_time,IDcardNo,face_idcard,idcardtype,department_id,Employetype_id 的本地化字符串。
        /// </summary>
        internal static string StaffKeys {
            get {
                return ResourceManager.GetString("StaffKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名,邮箱地址,电话号码,员工编号,照片路径,添加日期,身份证号码,门禁卡号,门禁卡号位数,部门,员工分类 的本地化字符串。
        /// </summary>
        internal static string StaffNames {
            get {
                return ResourceManager.GetString("StaffNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照 的本地化字符串。
        /// </summary>
        internal static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或者密码错误 的本地化字符串。
        /// </summary>
        internal static string UsernameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄码 的本地化字符串。
        /// </summary>
        internal static string YellowCode {
            get {
                return ResourceManager.GetString("YellowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
